### ISSUE TITLE
Selling firearms w/many attachments on the Flea Market generates an error TypeError: Cannot read properties of undefined (reading 'StackObjeectsCount')

### ISSUE THREAD

**Issue by Wicaeed** [IhanaMies/LootValue#13]
Often when selling a firearm on the Flea Market via the shortcut in this mod, most will be fine, however some will generate a server backend error and require the client to be restarted:
```
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
    at RagfairTaxService.calculateItemWorth (C:\snapshot\src\services\RagfairTaxService.ts:126:36)
    at RagfairTaxService.calculateTax (C:\snapshot\src\services\RagfairTaxService.ts:63:32)
    at RagfairController.chargePlayerTaxFee (C:\snapshot\src\controllers\RagfairController.ts:741:38)
    at RagfairController.createSingleOffer (C:\snapshot\src\controllers\RagfairController.ts:463:45)
    at RagfairController.addPlayerOffer (C:\snapshot\src\controllers\RagfairController.ts:392:29)
    at RagfairCallbacks.addOffer (C:\snapshot\src\callbacks\RagfairCallbacks.ts:88:39)
    at RagfairItemEventRouter.handleItemEvent (C:\snapshot\src\routers\item_events\RagfairItemEventRouter.ts:29:46)
    at ItemEventRouter.handleEvents (C:\snapshot\src\routers\ItemEventRouter.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ItemEventCallbacks.handleEvents (C:\snapshot\src\callbacks\ItemEventCallbacks.ts:22:31)
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
    at RagfairTaxService.calculateItemWorth (C:\snapshot\src\services\RagfairTaxService.ts:126:36)
    at RagfairTaxService.calculateTax (C:\snapshot\src\services\RagfairTaxService.ts:63:32)
    at RagfairController.chargePlayerTaxFee (C:\snapshot\src\controllers\RagfairController.ts:741:38)
    at RagfairController.createSingleOffer (C:\snapshot\src\controllers\RagfairController.ts:463:45)
    at RagfairController.addPlayerOffer (C:\snapshot\src\controllers\RagfairController.ts:392:29)
    at RagfairCallbacks.addOffer (C:\snapshot\src\callbacks\RagfairCallbacks.ts:88:39)
    at RagfairItemEventRouter.handleItemEvent (C:\snapshot\src\routers\item_events\RagfairItemEventRouter.ts:29:46)
    at ItemEventRouter.handleEvents (C:\snapshot\src\routers\ItemEventRouter.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ItemEventCallbacks.handleEvents (C:\snapshot\src\callbacks\ItemEventCallbacks.ts:22:31)
```

I'm trying to track down the cause of the error, and it seems to be associated with how many attachments a weapon has when it is sold via the LootValue shortcut.

 Listing a gun that had previously crashed the client when it was attempted to be sold by LootValue shortcut, via normal on the Flea Market & setting a value manually allows the gun to be listed for sale without error.

Server Modlist:
```
{
  "order": [
    "fika-server",
    "AAAArtemTrader",
    "AAArtemEquipment",
    "acidphantasm-scorpion",
    "aMoxoPixel-Painter",
    "MoxoPixel-MagTape",
    "Virtual's Custom Quest Loader",
    "WTT-PackNStrap",
    "WTT-HeadVoiceSelector",
    "WTT-The Long Lost Heads of Yojenkz",
    "ExpandedTaskText",
    "Fontaine-FOV-Fix",
    "tyfon-uifixes",
    "HD Vanilla Trader Pics",
    "Jehree-GildedKeyStorage",
    "mattdokn-insuranceplus",
    "MoreCheckmarksBackend",
    "revingly-micc",
    "DrakiaXYZ-LiveFleaPrices",
    "redlaser42-Increase Climb Height",
    "BRNVG_N-15Adapter",
    "Corter-ModSync",
    "ChooChoo-TraderModding",
    "odt-iteminfo",
    "ServerValueModifier",
    "IhanaMies-LootValueBackend",
    "tomanw-realisticpmcweapons",
    "acidphantasm-progressivebotsystem",
    "Skwizzy-LootingBots-ServerMod",
    "DanW-SPTQuestingBots",
    "SWAG",
    "zSolarint-SAIN-ServerMod",
    "zzMusicManiac-KeysInLoot"
  ]
}
```

![image](https://github.com/user-attachments/assets/0288bdf6-e3e2-49aa-b874-76848773c73e)

**Comment by maxomatic458** [comment]
@Wicaeed is your SPT profile converted from 3.8 to 3.9 by any chance?

I did this, and when using the 3.9 version of the mod i first noticed this.

**Comment by xThomate** [comment]
I have the problem when selling items with Attachments, it could be related to some items not being able to be listed on the fleemarket or the mod not being able to deattach the items. Quick-Selling items works just fine, at least for me.
