### ISSUE TITLE
Selling Items can lead to an error

### ISSUE THREAD

**Issue by maxomatic458** [IhanaMies/LootValue#15]
Sometimes selling items (seems to happen more often with assembled items like guns)

this error here can appear in the server console when trying to sell on the flea market via the keybind.

The game will be stuck, and the item that should be sent is stuck at loading.
When this happens, the game either needs to be restarted, or you need to wait until you receive an error in game

```
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
    at RagfairTaxService.calculateItemWorth (/snapshot/src/services/RagfairTaxService.ts:126:36)
    at RagfairTaxService.calculateTax (/snapshot/src/services/RagfairTaxService.ts:63:32)
    at RagfairController.chargePlayerTaxFee (/snapshot/src/controllers/RagfairController.ts:741:38)
    at RagfairController.createSingleOffer (/snapshot/src/controllers/RagfairController.ts:463:45)
    at RagfairController.addPlayerOffer (/snapshot/src/controllers/RagfairController.ts:392:29)
    at RagfairCallbacks.addOffer (/snapshot/src/callbacks/RagfairCallbacks.ts:88:39)
    at RagfairItemEventRouter.handleItemEvent (/snapshot/src/routers/item_events/RagfairItemEventRouter.ts:29:46)
    at ItemEventRouter.handleEvents (/snapshot/src/routers/ItemEventRouter.ts:36:35)
    at ItemEventCallbacks.handleEvents (/snapshot/src/callbacks/ItemEventCallbacks.ts:22:58)
    at RouteAction.action (/snapshot/src/routers/static/ItemEventStaticRouter.ts:19:52)
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
TypeError: Cannot read properties of undefined (reading 'StackObjectsCount')
    at RagfairTaxService.calculateItemWorth (/snapshot/src/services/RagfairTaxService.ts:126:36)
    at RagfairTaxService.calculateTax (/snapshot/src/services/RagfairTaxService.ts:63:32)
    at RagfairController.chargePlayerTaxFee (/snapshot/src/controllers/RagfairController.ts:741:38)
    at RagfairController.createSingleOffer (/snapshot/src/controllers/RagfairController.ts:463:45)
    at RagfairController.addPlayerOffer (/snapshot/src/controllers/RagfairController.ts:392:29)
    at RagfairCallbacks.addOffer (/snapshot/src/callbacks/RagfairCallbacks.ts:88:39)
    at RagfairItemEventRouter.handleItemEvent (/snapshot/src/routers/item_events/RagfairItemEventRouter.ts:29:46)
    at ItemEventRouter.handleEvents (/snapshot/src/routers/ItemEventRouter.ts:36:35)
    at ItemEventCallbacks.handleEvents (/snapshot/src/callbacks/ItemEventCallbacks.ts:22:58)
    at RouteAction.action (/snapshot/src/routers/static/ItemEventStaticRouter.ts:19:52)
```

**Comment by maxomatic458** [comment]
oh yea didnt see that one, closing as this is a duplicate of #13
